# Generated by Django 3.0.6 on 2020-08-18 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hit', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='d', max_length=20, null=True)),
                ('city_address_of_bookstore', models.CharField(max_length=20)),
                ('specific_address', models.TextField()),
                ('bookstore_information', models.TextField()),
                ('bookstore_image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation_about_bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(default=0)),
                ('comment_about_bookstore_with_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('traits', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstore_image', models.ImageField(blank=True, upload_to='image')),
                ('bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnechaekbang.Bookstore')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_contents', models.CharField(max_length=200)),
                ('comment_writer', models.CharField(max_length=100)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dongnechaekbang.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Bookstore_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_date', models.DateField(auto_now=True)),
                ('bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnechaekbang.Bookstore')),
            ],
        ),
        migrations.AddField(
            model_name='bookstore',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnechaekbang.Trait'),
        ),
    ]
